# Site settings
title: Multiprizer
email: contact@multiprizer.io
description: > 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://multiprizer.io" # the base hostname & protocol for your site

twitter_username: "multiprizer"
github_username: kombos

# Build settings
markdown: kramdown
